#!/bin/bash

home=$home

cd $home

echo "*******************"
echo "In Home Directory"
echo "*******************"

echo "*******************"
echo "Installing pip and git"
echo "*******************"

sudo apt-get install python3-pip

python3 -m pip install --upgrade pip

sudo apt-get install git

echo "*******************"
echo "Clone the repo"
echo "*******************"

git clone --recurse-submodules https://github.com/shardrv/tank_code_ws.git

echo "*******************"
pwd
echo "*******************"

cd tank_code_ws

echo "cpppo PLC simulation library"

pip install cpppo

echo "*******************"
echo "Now installing libplctag PLC communication library"
echo "*******************"
cd submodule/libplctag
mkdir -p build
cd build
cmake ..
make
sudo make install

echo "*******************"
echo "Now going back to build the code"
echo "*******************"
cd
cd tank_code_ws
mkdir -p build
cd build
cmake ..
make

export LD_LIBRARY_PATH=~/$home/tank_code_ws/submodule/libplctag:$LD_LIBRARY_PATH
sudo ldconfig

echo "*******************"
echo "*******************"
echo "ALL DONE"
echo "Now navigate to build folder and run ./cooling_tank"
